// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: reset.sql

package database

import (
	"context"
)

const resetChirpsTable = `-- name: ResetChirpsTable :exec
DELETE FROM chirps
`

func (q *Queries) ResetChirpsTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetChirpsTable)
	return err
}

const resetRefreshTokensTable = `-- name: ResetRefreshTokensTable :exec
DELETE FROM refresh_tokens
`

func (q *Queries) ResetRefreshTokensTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetRefreshTokensTable)
	return err
}

const resetUserTable = `-- name: ResetUserTable :exec
DELETE FROM users
`

func (q *Queries) ResetUserTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetUserTable)
	return err
}
